sudo: false

language: node_js

node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'

branches:
  only:
    - master
    - development
    - travis-ci

before_install:
  - npm install
  - npm install istanbul coveralls
