#!/bin/sh

set -e

echo ""

sed -i -e 's/process.nextTick/setImmediate/' node_modules/abstract-leveldown/testCommon.js

(proof run t/*/*.t.js | tee .proof.out | proof progress) || (proof errors < .proof.out) || exit 1

if [ "$TRAVIS" = "true" ]; then
  echo "running with coverage"
  t/cover

  echo "submitting to coveralls.io"
  (cat coverage/lcov.info | node_modules/.bin/coveralls) > /dev/null 2>&1

  curl 'https://www.prettyrobots.com/travisty' | sh
fi

echo ""
